### PR TITLE
Update MapTemplate.php fof-upload 1.5.0

### PR DESCRIPTION
**Pull request by Litalino**
Upload by FriendsOfFlarum V1.5.0

### CODE REVIEW

**Comment by Litalino** [comment]
Currently this utility still conflicts with rss  and flarum 1.8.4

**Comment by SKevo18** [comment]
Happens at FreeFlarum as well, could the PR be merged in its current state?

**Comment by JeromeGillard** [comment]
Nice work, thanks 👍

**Comment by JeromeGillard** [comment]
Deployed as [v0.1.9](https://packagist.org/packages/jeromegillard/map#v0.1.9).

**Pull request merged**
